# Generated by Django 6.1.1 on 2026-09-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_programsection_options_programsection_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsection',
            name='course',
            field=models.CharField(blank=True, default='', help_text='Legacy course code retained during migration (e.g., BSIT, BSCS, BSEMC, BSA, BSCrim)', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.CharField(blank=True, default='', help_text='Legacy course code retained during migration', max_length=50),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.program')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['program__code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='programsection',
            name='course_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_sections', to='core.course'),
        ),
        migrations.AddField(
            model_name='section',
            name='course_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('program', 'code'), name='unique_course_per_program'),
        ),
    ]
