# Generated by Django 6.1.1 on 2026-09-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_course_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.course'),
        ),
    ]
