# Generated by Django 6.1.1 on 2026-09-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_academic_filter_indexes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendancerecord',
            table='attendance_records',
        ),
        migrations.AlterModelTable(
            name='attendancesession',
            table='attendance_sessions',
        ),
        migrations.AlterModelTable(
            name='course',
            table='academic_courses',
        ),
        migrations.AlterModelTable(
            name='program',
            table='academic_programs',
        ),
        migrations.AlterModelTable(
            name='programsection',
            table='academic_section_definitions',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='academic_schedules',
        ),
        migrations.AlterModelTable(
            name='section',
            table='academic_class_sections',
        ),
        migrations.AlterModelTable(
            name='studentsection',
            table='academic_enrollments',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='academic_subjects',
        ),
    ]
