# Generated by Django 6.1.1 on 2026-09-27 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_tables_db_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_day_rows', to='core.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Day',
                'verbose_name_plural': 'Schedule Days',
                'db_table': 'academic_schedule_days',
                'ordering': ['schedule_id', 'day_of_week'],
                'unique_together': {('schedule', 'day_of_week')},
            },
        ),
    ]
