# Generated by Django 6.1.1 on 2026-09-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_attendancesessionreopenaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are temporarily closed and hidden from new activity.'),
        ),
        migrations.AddField(
            model_name='programsection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are temporarily closed and hidden from new activity.'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are temporarily closed and hidden from new activity.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are temporarily closed and hidden from new activity.'),
        ),
    ]
