# Generated by Django 6.1.1 on 2026-09-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_birth_date_student_birth_place_and_more'),
        ('core', '0010_alter_programsection_course_alter_section_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, help_text='Legacy course code retained during migration', max_length=100),
        ),
    ]
