# Generated by Django 6.1.1 on 2026-09-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_course_ref_alter_student_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_profiles',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher_profiles',
        ),
    ]
