# Generated by Django 6.1.1 on 2026-09-27 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_tables_db_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBiometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='face_images/')),
                ('face_enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Student Biometric',
                'verbose_name_plural': 'Student Biometrics',
                'db_table': 'student_biometrics',
            },
        ),
    ]
