# Generated by Django 6.1.1 on 2026-09-29 03:29

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_emp_to_fac_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[accounts.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/', validators=[accounts.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='studentbiometric',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/', validators=[accounts.validators.validate_image_upload]),
        ),
    ]
