# Generated by Django 6.1.1 on 2026-09-29 05:25

import accounts.validators
import attendance_fr.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_revoked_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, storage=attendance_fr.storage.get_face_storage, upload_to='face_images/', validators=[accounts.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='studentbiometric',
            name='face_image',
            field=models.ImageField(blank=True, null=True, storage=attendance_fr.storage.get_face_storage, upload_to='face_images/', validators=[accounts.validators.validate_image_upload]),
        ),
    ]
