import { resolveMediaUrl } from '../../api';
import React from 'react';
import { TableLoadingRow } from '../../ui';
import { AlertTriangle, CheckCircle, GraduationCap, Search } from 'lucide-react';

export default function StudentEnrollmentTable({ students, loading, search, onSearchChange, onOpenFaceModal, onRegister }) {
  return <div className="card"><div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px' }}><span className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><GraduationCap size={16} /> Registered Students <span className="badge badge-info">{students.length}</span></span><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ position: 'relative' }}><Search size={14} style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} /><input className="form-control filter-control" placeholder="Search student or ID..." value={search} onChange={(event) => onSearchChange(event.target.value)} style={{ paddingLeft: '32px', width: '220px' }} /></div><button type="button" className="btn btn-outline btn-sm" onClick={onRegister}>Enroll Student</button></div></div><div className="table-container" style={{ border: 'none', margin: 0 }}><table><thead><tr><th>Student</th><th>Student ID</th><th>Course &amp; Year</th><th>Face Status</th><th style={{ textAlign: 'right' }}>Action</th></tr></thead><tbody>{loading ? <TableLoadingRow colSpan={5} label="Loading students…" /> : students.length === 0 ? <tr><td colSpan="5" className="text-center text-muted" style={{ padding: '40px' }}><GraduationCap size={40} style={{ opacity: 0.4 }} /><p>No students match your search.</p><button type="button" className="btn btn-primary" onClick={onRegister}>Register Student</button></td></tr> : students.map((student) => <StudentRow key={student.id} student={student} onOpenFaceModal={onOpenFaceModal} />)}</tbody></table></div></div>;
}

function StudentRow({ student, onOpenFaceModal }) {
  const imageUrl = resolveMediaUrl(student.face_image);
  const enrolled = !!student.face_image; // Student is enrolled if they have a face image
  const fallbackAvatar = `https://ui-avatars.com/api/?name=${encodeURIComponent(`${student.user?.first_name || ''} ${student.user?.last_name || ''}`.trim() || 'Student')}&background=6366f1&color=fff`;
  return <tr><td><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>{imageUrl ? <img src={imageUrl} alt="" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = fallbackAvatar; }} style={{ width: '36px', height: '36px', borderRadius: '50%', objectFit: 'cover', border: '2px solid var(--success)' }} /> : <div style={{ width: '36px', height: '36px', borderRadius: '50%', background: 'var(--bg-secondary)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700, color: 'var(--primary)' }}>{(student.user?.first_name?.[0] || 'S').toUpperCase()}</div>}<div><strong>{student.user?.first_name} {student.user?.last_name}</strong><div className="text-muted" style={{ fontSize: '11px' }}>{student.user?.email}</div></div></div></td><td><code>{student.student_id}</code></td><td><strong>{student.display_academic_program || student.course || 'BSIT'}</strong><span className="text-muted"> — Year {student.year_level || 1}</span></td><td>{enrolled ? <span className="badge badge-success"><CheckCircle size={13} /> Enrolled</span> : <span className="badge badge-warning"><AlertTriangle size={13} /> Not Enrolled</span>}</td><td style={{ textAlign: 'right' }}><button type="button" className={`btn btn-sm ${enrolled ? 'btn-outline' : 'btn-success'}`} onClick={() => onOpenFaceModal(student)}>{enrolled ? 'Re-enroll' : 'Enroll Face'}</button></td></tr>;
}
